add_newline = false
command_timeout = 1000

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$python\
$shell\
$shlvl\
$sudo\
$line_break\
$character
"""
right_format = """
$cmd_duration\
$status
"""

[line_break]
disabled = false

[cmd_duration]
format = " [$duration](bold yellow)"
disabled = false

[status]
style = "bold yellow"
format = '[\[$common_meaning$signal_name$maybe_int\]]($style)'
disabled = true

[shell]
disabled = false
format = "[$indicator]($style):"

[character]
disabled = false
error_symbol = " [✗](bold red) "
format = "$symbol"
success_symbol = " [➜](bold green) "

[directory]
disabled = false
format = ":[$path]($style)[$read_only]($read_only_style) "
style = "bold blue"

[git_branch]
disabled = false
always_show_remote = true
format = "[$symbol$branch]($style) "
style = "bold yellow"
symbol = ""

[git_commit]
disabled = false
commit_hash_length = 5
format = "[$hash]($style)[$tag]($style)"
only_detached = false
style = "bold yellow"

[git_status]
disabled = false
style = "bold yellow"
format = "[$all_status$ahead_behind]($style)"
ahead = '↑$count '
behind = '↓$count '
conflicted = '=$count '
deleted = '✗$count '
diverged = '⇕$count '
modified = '!$count '
renamed = '»$count '
staged = '+$count '
stashed = '\$$count '
untracked = '?$count '
up_to_date = '✓$count '

[hostname]
disabled = false
format = "[@$hostname]($style)"
ssh_only = false
style = "green bold"

[username]
disabled = false
format = "[$user]($style)"
show_always = true
style_root = "red bold"
style_user = "green bold"

[python]
format = "[$symbol$version]($style) "
style = "bold green"

[sudo]
format = "[$symbol]($style)"
symbol = "💀" 
style = "bold red"
disabled = false

[shlvl]
threshold = 1
repeat = false
style = "bold yellow"
format = "[$shlvl]($style)"
disabled = false


